version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: server
    hostname: server
    ports:
      - "8081:80"
    volumes:
      - ./:/code
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    image: php:7.4-fpm
    container_name: php
    hostname: php
    build:
      context: ./docker/php
    env_file:
      - .env
    volumes:
      - ./:/code
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
